id = "leander"
name = "Leander"
description = "Enhanced and idiomatic Zed support for Lean 4"
version = "0.4.0"
schema_version = 1
authors = ["Gabriel <gabriel@minatel.dev>"]
repository = "https://github.com/SrGaabriel/leander"
snippets = "snippets/lean 4.json"

[language_servers.leander-proxy]
name = "Leander Proxy"
languages = ["Lean 4"]

[grammars.lean]
repository = "https://github.com/Julian/tree-sitter-lean"
rev = "efe6b87145608d12f5996bd7f0cf6095a0e82261"

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["**"]
