id = "lean-to"
name = "Lean-to"
description = "Support for Lean 4 and the infoview in Zed."
version = "0.2.3"
schema_version = 1
authors = ["Gabriel <gabriel@minatel.dev>"]
repository = "https://github.com/SrGaabriel/lean-to"
snippets = "snippets/lean 4.json"

[language_servers.lean-to-proxy]
name = "Lean-to Proxy"
languages = ["Lean 4"]

[grammars.lean]
repository = "https://github.com/Julian/tree-sitter-lean"
rev = "efe6b87145608d12f5996bd7f0cf6095a0e82261"

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["**"]
